In [3]:
import numpy as np
marks = np.array([[85, 78, 92],
                  [76, 88, 90],
                  [90, 95, 85],
                  [70, 60, 75],
                  [88, 82, 91]])
print("Student Marks:\n", marks)
# Calculate average marks for each student
average_marks = np.mean(marks, axis=1)
print("\nAverage Marks for each student:\n", average_marks)

# Calculate minimum marks for each student
min_marks = np.min(marks, axis=1)
print("\nMinimum Marks for each student:\n", min_marks)

# Calculate maximum marks for each student
max_marks = np.max(marks)
print("\nMaximum Marks for each student:\n", max_marks)

# Calculate average marks for each subject
average_subject_marks = np.mean(marks)
print("\nAverage Marks for each subject:\n", average_subject_marks)

Student Marks:
 [[85 78 92]
 [76 88 90]
 [90 95 85]
 [70 60 75]
 [88 82 91]]

Average Marks for each student:
 [85.         84.66666667 90.         68.33333333 87.        ]

Minimum Marks for each student:
 [78 76 85 60 82]

Maximum Marks for each student:
 95

Average Marks for each subject:
 83.0


In [4]:
import pandas as pd
# Creating a dictionary with employee details
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT'],
    'Salary': [60000, 45000, 70000, 55000, 48000]
}

# Creating a DataFrame from the dictionary
df = pd.DataFrame(data)
print("Employee DataFrame:\n", df)
# Filtering employees with salary > 50,000
high_salary_employees = df[df['Salary'] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_salary_employees)
# Sorting the DataFrame by Salary in descending order
sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nSorted DataFrame by Salary (Descending):\n", sorted_df)
# Adding a new column for Bonus (10% of Salary)
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus Column:\n", df)
# Calculating total salary expense including bonuses
total_salary_expense = df['Salary'].sum() + df['Bonus'].sum()
print("\nTotal Salary Expense (including bonuses):", total_salary_expense)
# Saving the DataFrame to a CSV file
df.to_csv('employee_details.csv', index=False)
print("\nDataFrame saved to 'employee_details.csv'")

Employee DataFrame:
       Name   ID Department  Salary
0    Alice  101         HR   60000
1      Bob  102         IT   45000
2  Charlie  103    Finance   70000
3    David  104  Marketing   55000
4      Eva  105         IT   48000

Employees with Salary > 50,000:
       Name   ID Department  Salary
0    Alice  101         HR   60000
2  Charlie  103    Finance   70000
3    David  104  Marketing   55000

Sorted DataFrame by Salary (Descending):
       Name   ID Department  Salary
2  Charlie  103    Finance   70000
0    Alice  101         HR   60000
3    David  104  Marketing   55000
4      Eva  105         IT   48000
1      Bob  102         IT   45000

DataFrame with Bonus Column:
       Name   ID Department  Salary   Bonus
0    Alice  101         HR   60000  6000.0
1      Bob  102         IT   45000  4500.0
2  Charlie  103    Finance   70000  7000.0
3    David  104  Marketing   55000  5500.0
4      Eva  105         IT   48000  4800.0

Total Salary Expense (including bonuses): 305800.0

